# Generated by Django 3.2.4 on 2021-08-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meriapp', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
